

export const AppConfig = {
  api_version: 43,
  scopes: [
    "channel:manage:broadcast",
    "channel:read:goals",
    "moderator:read:followers",
    "channel:manage:vips",
    "channel:read:hype_train",
    "channel:manage:clips",
    "channel:read:redemptions",
    "channel:manage:redemptions",
    "clips:edit",
    "user:read:moderated_channels",
    "moderator:read:chatters",
  ],
  word_list_bin_id: "XjEbxLQL",

  route_names: {
    botw: "Breath of the Wild"
  },
  routes: {
    botw: {
      "great-plateau": [
        {
          order: 1,
          name: "The Shrine of Resurrection",
          categoryName: "The Journey Begins: Great Plateau",
          categoryId: "great-plateau",
          id: "shrine-of-resurrection",
          description: "Awakening & The Shrine of Resurrection: Starting the adventure, obtaining the Sheikah Slate.",
        },
        {
          order: 2,
          name: "Exploring the Plateau",
          categoryName: "The Journey Begins: Great Plateau",
          categoryId: "great-plateau",
          id: "exploring-the-plateau",
          description: "Exploring the Plateau: Learning basic mechanics, survival, and combat.",
        },
        {
          order: 3,
          name: "The Plateau Towers & Shrines",
          categoryName: "The Journey Begins: Great Plateau",
          categoryId: "great-plateau",
          id: "plateau-towers-and-shrines",
          description: "Activating the Great Plateau Tower and completing the four initial shrines (Oman Au, Ja Baij, Owa Daim, Keh Namut) to earn Runes and Spirit Orbs.",
        },
        {
          order: 4,
          name: "Meeting the Old Man",
          categoryName: "The Journey Begins: Great Plateau",
          categoryId: "great-plateau",
          id: "meeting-the-old-man",
          description: "Uncovering his identity and receiving the Paraglider.",
        },
        {
          order: 5,
          name: "Leaving the Plateau",
          categoryName: "The Journey Begins: Great Plateau",
          categoryId: "great-plateau",
          id: "leaving-the-plateau",
          description: "Gliding down into the wider kingdom of Hyrule.",
        },
      ],
      "seeking-guidance": [
        {
          order: 1,
          name: "Journey to Kakariko Village",
          categoryName: "Seeking Guidance & Unlocking Potential",
          categoryId: "seeking-guidance",
          id: "journey-to-kakariko-village",
          description: "Navigating Hyrule Field, first encounters, reaching the village.",
        },
        {
          order: 2,
          name: "Meeting Impa",
          categoryName: "Seeking Guidance & Unlocking Potential",
          categoryId: "seeking-guidance",
          id: "meeting-impa",
          description: "Receiving the 'Seek Out Impa' main quest objective and learning about the Divine Beasts and Calamity Ganon.",
        },
        {
          order: 3,
          name: "Hateno Village & Ancient Tech Lab",
          categoryName: "Seeking Guidance & Unlocking Potential",
          categoryId: "seeking-guidance",
          id: "hateno-village-and-ancient-tech-lab",
          description: "Journeying east, activating Hateno Tower, meeting Purah and Symin, upgrading the Sheikah Slate (Camera, Hyrule Compendium, Sheikah Sensor+).",
        },
        {
          order: 4,
          name: "Locked Mementos",
          categoryName: "Seeking Guidance & Unlocking Potential",
          categoryId: "seeking-guidance",
          id: "locked-mementos",
          description: "Starting the quest to recover Link's lost memories.",
        },
      ],
      "zoras-domain": [
        {
          order: 1,
          name: "Reaching Zora's Domain",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "zoras-domain",
          id: "reaching-zoras-domain",
          description: "Following the path, meeting Prince Sidon.",
        },
        {
          order: 2,
          name: "Meeting the Zora King & Elders",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "zoras-domain",
          id: "meeting-the-zora-king-and-elders",
          description: "Gaining access to the Divine Beast questline.",
        },
        {
          order: 3,
          name: "Gathering Shock Arrows",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "zoras-domain",
          id: "gathering-shock-arrows",
          description: "Preparing for the approach.",
        },
        {
          order: 4,
          name: "Boarding Vah Ruta",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "zoras-domain",
          id: "boarding-vah-ruta",
          description: "The battle on the water with Sidon.",
        },
        {
          order: 5,
          name: "Inside Divine Beast Vah Ruta",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "zoras-domain",
          id: "inside-divine-beast-vah-ruta",
          description: "Solving the water-based puzzles, activating terminals.",
        },
        {
          order: 6,
          name: "Defeating Waterblight Ganon",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "zoras-domain",
          id: "defeating-waterblight-ganon",
          description: "Claiming Mipha's Grace.",
        },
      ],
      "goron-city": [
        {
          order: 1,
          name: "Reaching Goron City",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "goron-city",
          id: "reaching-goron-city",
          description: "Navigating Eldin's heat, reaching the city.",
        },
        {
          order: 2,
          name: "Meeting the Goron Boss Bludo",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "goron-city",
          id: "meeting-the-goron-boss-bludo",
          description: "Learning about Rudania's rampage.",
        },
        {
          order: 3,
          name: "Rescuing Yunobo",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "goron-city",
          id: "rescuing-yunobo",
          description: "Stealth mission in the Northern Mine.",
        },
        {
          order: 4,
          name: "Assaulting Vah Rudania",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "goron-city",
          id: "assaulting-vah-rudania",
          description: "Ascending Death Mountain with Yunobo.",
        },
        {
          order: 5,
          name: "Inside Divine Beast Vah Rudania",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "goron-city",
          id: "inside-divine-beast-vah-rudania",
          description: "Solving fire and darkness puzzles, activating terminals.",
        },
        {
          order: 6,
          name: "Defeating Fireblight Ganon",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "goron-city",
          id: "defeating-fireblight-ganon",
          description: "Claiming Daruk's Protection.",
        },
      ],
      "rito-village": [
        {
          order: 1,
          name: "Reaching Rito Village",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "rito-village",
          id: "reaching-rito-village",
          description: "Traversing Tabantha, activating the tower.",
        },
        {
          order: 2,
          name: "Meeting the Rito Elder Kaneli",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "rito-village",
          id: "meeting-the-rito-elder-kaneli",
          description: "Learning about Medoh's threat.",
        },
        {
          order: 3,
          name: "Assisting Teba",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "rito-village",
          id: "assisting-teba",
          description: "Proving archery skills at the Flight Range.",
        },
        {
          order: 4,
          name: "Airborne Assault on Vah Medoh",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "rito-village",
          id: "airborne-assault-on-vah-medoh",
          description: "Attacking the cannons with Teba.",
        },
        {
          order: 5,
          name: "Inside Divine Beast Vah Medoh",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "rito-village",
          id: "inside-divine-beast-vah-medoh",
          description: "Solving wind and tilting puzzles, activating terminals.",
        },
        {
          order: 6,
          name: "Defeating Windblight Ganon",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "rito-village",
          id: "defeating-windblight-ganon",
          description: "Claiming Revali's Gale.",
        },
      ],
      "gerudo-town": [
        {
          order: 1,
          name: "Reaching Gerudo Town",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "gerudo-town",
          id: "reaching-gerudo-town",
          description: "Crossing the Gerudo Desert, gaining entry (disguise).",
        },
        {
          order: 2,
          name: "Meeting Gerudo Chief Riju",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "gerudo-town",
          id: "meeting-gerudo-chief-riju",
          description: "Learning about Naboris and the stolen Thunder Helm.",
        },
        {
          order: 3,
          name: "Infiltrating the Yiga Clan Hideout",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "gerudo-town",
          id: "infiltrating-the-yiga-clan-hideout",
          description: "Retrieving the Thunder Helm.",
        },
        {
          order: 4,
          name: "Sand Seal Assault on Vah Naboris",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "gerudo-town",
          id: "sand-seal-assault-on-vah-naboris",
          description: "Riding with Riju to disable the beast.",
        },
        {
          order: 5,
          name: "Inside Divine Beast Vah Naboris",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "gerudo-town",
          id: "inside-divine-beast-vah-naboris",
          description: "Solving electricity and rotation puzzles, activating terminals.",
        },
        {
          order: 6,
          name: "Defeating Thunderblight Ganon",
          categoryName: "Freeing the Divine Beasts",
          categoryId: "gerudo-town",
          id: "defeating-thunderblight-ganon",
          description: "Claiming Urbosa's Fury.",
        },
      ],
      "masters-sword-and-past": [
        {
          order: 1,
          name: "The Master Sword",
          categoryName: "The Hero's Blade & Recovered Past",
          categoryId: "masters-sword-and-past",
          id: "the-master-sword",
          description: "Journeying to Korok Forest, navigating the Lost Woods, passing the Korok Trials (optional but recommended), claiming the legendary sword (requires 13+ heart containers).",
        },
        {
          order: 2,
          name: "Recovering Lost Memories",
          categoryName: "The Hero's Blade & Recovered Past",
          categoryId: "masters-sword-and-past",
          id: "recovering-lost-memories",
          description: "Finding all memory locations triggered by the 'Locked Mementos' photos, uncovering Link's past with Zelda and the Champions.",
        },
      ],
      "confronting-the-calamity": [
        {
          order: 1,
          name: "Infiltrating Hyrule Castle",
          categoryName: "Confronting the Calamity",
          categoryId: "confronting-the-calamity",
          id: "infiltrating-hyrule-castle",
          description: "Breaching the castle grounds, navigating the corrupted interior, facing powerful enemies.",
        },
        {
          order: 2,
          name: "Defeating Calamity Ganon",
          categoryName: "Confronting the Calamity",
          categoryId: "confronting-the-calamity",
          id: "defeating-calamity-ganon",
          description: "The final battle sequence, utilizing the Divine Beasts' power (if freed).",
        },
        {
          order: 3,
          name: "Destroying Dark Beast Ganon",
          categoryName: "Confronting the Calamity",
          categoryId: "confronting-the-calamity",
          id: "destroying-dark-beast-ganon",
          description: "The ultimate confrontation in Hyrule Field.",
        },
      ],
      // "shrines-and-collectibles": [
      //   {
      //     order: 1,
      //     name: "Shrines of Trials",
      //     categoryName: "Side Quests & Collectibles",
      //     categoryId: "shrines-and-collectibles",
      //     id: "shrines-of-trials",
      //     description: "Locating and completing all 120 base game Shrines (plus DLC shrines if applicable) for Spirit Orbs (Heart Containers/Stamina Vessels). Includes Shrine Quests.",
      //   },
      //   {
      //     order: 2,
      //     name: "Korok Seeds",
      //     categoryName: "Side Quests & Collectibles",
      //     categoryId: "shrines-and-collectibles",
      //     id: "korok-seeds",
      //     description: "Finding all 900 Koroks hidden across Hyrule to expand inventory space via Hestu.",
      //   },
      //   {
      //     order: 3,
      //     name: "Side Quests",
      //     categoryName: "Side Quests & Collectibles",
      //     categoryId: "shrines-and-collectibles",
      //     id: "side-quests",
      //     description: "Completing all listed Side Quests obtained from NPCs throughout Hyrule, offering various rewards and stories.",
      //   },
      //   {
      //     order: 4,
      //     name: "Armor Sets & Upgrades",
      //     categoryName: "Side Quests & Collectibles",
      //     categoryId: "shrines-and-collectibles",
      //     id: "armor-sets-and-upgrades",
      //     description: "Finding all pieces of armor and fully upgrading them via the Great Fairy Fountains. Requires locating all Great Fairies.",
      //   },
      //   {
      //     order: 5,
      //     name: "Recovered Memories",
      //     categoryName: "Side Quests & Collectibles",
      //     categoryId: "shrines-and-collectibles",
      //     id: "recovered-memories",
      //     description: "Finding all memory locations (linked to Main Quest section).",
      //   },
      //   {
      //     order: 6,
      //     name: "Hyrule Compendium",
      //     categoryName: "Side Quests & Collectibles",
      //     categoryId: "shrines-and-collectibles",
      //     id: "hyrule-compendium",
      //     description: "Photographing all entries for Weapons, Bows & Arrows, Shields, Materials, Monsters, Treasure, and Fauna for Symin.",
      //   },
      //   {
      //     order: 7,
      //     name: "Medals of Honor",
      //     categoryName: "Side Quests & Collectibles",
      //     categoryId: "shrines-and-collectibles",
      //     id: "medals-of-honor",
      //     description: "Defeating all Talus, Hinox/Stalnox, and Molduga variations for Kilton.",
      //   },
      //   {
      //     order: 8,
      //     name: "Key Location Discovery",
      //     categoryName: "Side Quests & Collectibles",
      //     categoryId: "shrines-and-collectibles",
      //     id: "key-location-discovery",
      //     description: "Visiting and registering all named locations on the map (contributes to map percentage).",
      //   },
      // ],
    }
  }
};
